version: "3.7"

services:
  mariadb:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=Chahw7aev9re
      - MYSQL_DATABASE=ivis
      - MYSQL_USER=ivis
      - MYSQL_PASSWORD=Chahw7aev9re
    volumes:
      - arima-mariadb:/var/lib/mysql
    ports:
      - 9991:3306 # for debugging

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.3
    environment:
      - discovery.type=single-node
    volumes:
      - arima-elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9992:9200 # for debugging

  ivis:
    build: .
    image: arima-docker
    depends_on:
      - mariadb
    #command: sh -c "cd /opt/ivis/server && sleep 10 && node index.js"
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    environment:
      - NODE_ENV=arima
    volumes:
      - ./arima.yaml:/opt/ivis/server/config/arima.yaml

volumes:
  arima-mariadb:
  arima-elasticsearch: